### ISSUE TITLE
模版使用{% extends parentTemplate %}的时候替换路径不正确

### ISSUE THREAD

**Issue by tommyandjacky** [hefangshi/fis-parser-nunjucks#1]
如果模版中使用{% extends parentTemplate %}，即使用模版变量而不是模版路径，继承的模版是在运行时指定的，fis-parser-nunjucks没有处理此种情况导致出错。
另外还有一个疑问，在处理模版文件的时候自动依赖了同名的css文件？还有其它自动依赖么？

**Comment by hefangshi** [comment]
如果是运行时指定的extends，就无法在构建阶段分析出依赖自动加载了，所以只能使用模板路径

FIS会自动依赖同名的CSS，所以同名的CSS就不用自己写了，没有其他的自动依赖。

**Comment by hefangshi** [comment]
你说的{% extends parentTemplate %}这个写法，你确认nunjucks本身支持么？貌似原生预编译就无法支持。

**Comment by tommyandjacky** [comment]
nunjucks本身是[支持的](http://mozilla.github.io/nunjucks/templating.html#template-inheritance)，直接预编译也可以啊

```
> nunjucks.precompileString("{% extends parentLayout %} hello",{name:'hello'});

'(function() {(window.nunjucksPrecompiled = window.nunjucksPrecompiled || {})["h
ello"] = (function() {function root(env, context, frame, runtime, cb) {\nvar lin
eno = null;\nvar colno = null;\nvar output = "";\ntry {\nenv.getTemplate(runtime
.contextOrFrameLookup(context, frame, "parentLayout"), true, function(t_2,parent
Template) {\nif(t_2) { cb(t_2); return; }\nfor(var t_1 in parentTemplate.blocks)
 {\ncontext.addBlock(t_1, parentTemplate.blocks[t_1]);\n}\noutput += " hello";\n
parentTemplate.rootRenderFunc(env, context, frame, runtime, cb);\n});\n} catch (
e) {\n  cb(runtime.handleError(e, lineno, colno));\n}\n}\nreturn {\nroot: root\n
};\n})();\n})();\n'
```

编译之后模版名变成了runtime
.contextOrFrameLookup(context, frame, "parentLayout")

**Comment by tommyandjacky** [comment]
那么是否可以编译时指明这些变量呢

**Comment by hefangshi** [comment]
@tommyandjacky 确认了下，是插件的BUG，已经修复了，重新安装一下就可以使用了

``` javascript
$(function(){
    $.getJSON("shownews/shownews.json",function(data){
        var template = __inline('shownews.tmpl');
        data.parentLayout = "layouts/default/layout.tmpl";
        $("#wrapper").append(template(data));
    });
});
```

注意这里的路径是fis的文件ID，默认为绝对路径去掉前面的"/"，比如"/layouts/default/layout.tmpl"的文件ID为"layouts/default/layout.tmpl"

但是此时就需要自己主动去声明`layouts/default/layout.tmpl`的依赖了，因为这种依赖是无法从静态分析中获取的。

**Comment by tommyandjacky** [comment]
呵呵，主动声明依赖@require "layouts/default/layout.tmpl"，正好也是通过html-like文件聚合其相关的js和css，很牛逼很不错，多谢啦
